# Generated by Django 3.2.7 on 2021-11-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_ticket_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='salutation',
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.user'),
            preserve_default=False,
        ),
    ]
