# Generated by Django 3.2.7 on 2021-11-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20211123_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='special',
            field=models.CharField(default='Null', max_length=10000),
        ),
    ]
