# Generated by Django 3.2.7 on 2021-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_activity_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='special_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
