# Generated by Django 3.2.7 on 2021-11-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20211124_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='ticket',
        ),
    ]
