# Generated by Django 3.2.7 on 2021-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='headline',
            field=models.CharField(default='Null', max_length=10000),
        ),
    ]
